apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: msa
type: Opaque
data:
  password: YWRtaW4=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: msa
data:
  _DATASOURCE_ADDRESS: mysql:3306
  _DATASOURCE_TABLESPACE: store
  _DATASOURCE_USERNAME: root